### ISSUE TITLE
Uses for ConstantValueShape

### ISSUE THREAD

**Issue by bhgomes** [oschulz/ValueShapes.jl#1]
Hi, @oschulz! Thank you for a great package. I look forward to using it in some upcoming projects. I'm wondering what the uses/motivation behind the `ConstValueShape` type are. Could you provide some examples where you would want to use it over storing the constant value outside the table?

**Comment by oschulz** [comment]
Hi, @bhgomes, thanks! One of the motivations behind ShapesOfVariables is to use it in fitting/optimization applications. Often, fitters/optimizers will expect a flat vector of parameters, but may not allow you to pin some of them to constant values - so if one wants to fix parameters, they have to be kept out of the parameter vectors - that's what `ConstValueShape` does.

**Comment by bhgomes** [comment]
Thanks, @oschulz, that makes a lot of sense.
