### ISSUE TITLE
Non-Trivial Typing for Custom VarShapes

### ISSUE THREAD

**Issue by bhgomes** [oschulz/ValueShapes.jl#2]
Suppose I have some `VarShapes` of the form returned by this function:

```julia
function customshape(::Type{T}, N::Int)
    VarShapes(links=ArrayShape{Int}(3, 1), meta=ArrayShape{T}(N, 1))
end
```
How would I give the underlying data structure (`ElasticArray`?) the best typing (not `Any` or `Array{Any}`)? I know I could create a `TypedTables.Table` with these types by hand, but how would I do this with the `VarShapes` object?

**Comment by oschulz** [comment]
Hey, sorry, completely overlooked this!

**Comment by oschulz** [comment]
The idea is that the shape is abstract, it doesn't specify which array type (standard, elastic, ...) to use to represent the actual data. However, you can do this:

```julia
using ValueShapes, ArraysOfArrays, ElasticArrays
shape = NamedTupleShape(a = ArrayShape{Real}(3, 1), b = ArrayShape{Real}(3, 1))
data = VectorOfSimilarVectors{Float64}(shape)
resize!(flatview(data), totalndof(shape), 20)
shaped_data = shape.(data)
```
