### ISSUE TITLE
Trait-based Shapes

### ISSUE THREAD

**Issue by colinxs** [oschulz/ValueShapes.jl#3]
First off, awesome work Oliver! Between this and ElasticArrays/UnsafeArrays/ArraysOfArrays etc. you're a roll!

I'd been using something similar to this package in my own code, but took some inspiration from LabelledArrays and StaticArrays by placing all the shape information in the type and using @generated functions. The result is a zero-cost abstraction at runtime (after I fiddle with some more knobs...).

Anyways, I took some inspiration (and code!) from your package, cleaned some things up, and put it all together over [here](https://github.com/colinxs/Shapes.jl). It's very much WIP, but there's an example in the readme. If you think it's appropriate, we could migrate some of those features over here and work towards a single, canonical package for all things shape-related. 

Colin

**Comment by oschulz** [comment]
Hey, sorry, completely overlooked this!

**Comment by oschulz** [comment]
Are you still interested in porting over features from Shapes.jl?

**Comment by oschulz** [comment]
Closing this for now - @colinxs, please feel free to reopen if you're still interested.

**Comment by colinxs** [comment]
Sorry I missed this! I'm a bit slammed right now, but perhaps we can revisit this in the future? I think having a single package for describing shapes/schemas would be beneficial.

**Comment by oschulz** [comment]
No worries, I know how it is! Sure, we can reopen this any time!

**Comment by oschulz** [comment]
I did take a quick look at your package - from what I can see, you encode array sizes into the type parameters. I have a feeling that might be a problem for typical use cases with arrays arbitrary size, since it would put a high load on compiler and type system. But it would be ideal for static arrays (which ValueShapes doesn't support yet, but it's definitely a to-do item).
